server:
  jwt_secret: "srfrtt54tgg64"
  port: "8080"
db:
  user: "postgres"
  password: "102030dD"
  host: "localhost"
  port: "5432"
  dbname: "app"
mail:
  email: "boltushkaapp@gmail.com"
  password: "nwcbhfwbygjfwcmx"
